name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: k-paxian/dart-package-publisher@v1.6
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2.10.0
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter format --dry-run .
    - run: flutter analyze
    - run: flutter test
